title: Lina Herasymenko
description: > 
  Data Analyst Portfolio | Dashboards | Power BI | Tableau | SQL
theme: jekyll-theme-cayman
logo: /logo.png



# Додаткові налаштування
title: "Lina Herasymenko"
name: "Lina Herasymenko"
description: "Data Analyst Portfolio"
minimal_mistakes_skin: "sunrise"
