title: "Lina Herasymenko"
description: "Data Analyst Portfolio | Power BI | Tableau | SQL"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
locale: "en-US"
url: "https://linaherasymenko.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Lina Herasymenko"
  avatar: "/logo.png"
  bio: "Data Analyst passionate about data storytelling, dashboards and analytics"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lina-herasymenko"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/linaherasymenko"
